services:
  mysql: 
    image: mysql
    container_name: ignite-call-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - './data/mysql:/data/mysql'
