services:
  postgres: 
    image: postgres
    container_name: ignite-call
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ignitecall
    volumes:
      - './data/pg:/data/postgres'
